// Flat config (ESLint 9). Rules that encode architecture decisions carry their ADR.
import js from '@eslint/js';
import nextPlugin from '@next/eslint-plugin-next';
import importX from 'eslint-plugin-import-x';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/.next/**',
      '**/coverage/**',
      '**/node_modules/**',
      '**/*.tsbuildinfo',
      // Generated by Next.js on every build; not ours to lint.
      '**/next-env.d.ts',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    plugins: { 'import-x': importX },
    rules: {
      '@typescript-eslint/consistent-type-imports': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          // `const { omitted: _x, ...rest } = obj` is the idiomatic way to drop a key.
          ignoreRestSiblings: true,
        },
      ],

      // Catches the package-root form: '../../validation'. Resolves package.json
      // boundaries rather than guessing from path depth — a hand-rolled '../../*'
      // pattern also blocks legitimate intra-package imports (T-001).
      'import-x/no-relative-packages': 'error',
    },
  },

  // The import-x rule above resolves entry points, so a deep path into another
  // package's source ('../../validation/src/index') slips past it — verified.
  // Re-entering a 'src' directory after traversing up is cross-package by
  // construction, but ONLY for a file that is itself inside src: from there you never
  // climb back into your own. A sibling of src — apps/api/test — legitimately does,
  // and the rule flagged it as a cross-package import until this was scoped (T-006).
  {
    files: ['**/src/**/*.{ts,tsx,js,jsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['../**/src/**'],
              message:
                'Deep relative import into another package. Depend on the workspace package (@investigator/*) and its public entry point instead — T-001.',
            },
          ],
        },
      ],
    },
  },

  // ADR-0004: packages/ui is web-only. shadcn, Cult UI and React Bits are DOM
  // libraries and will break the React Native build. Share tokens, never components.
  {
    files: ['apps/mobile/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: '@investigator/ui',
              message:
                'packages/ui is web-only (ADR-0004). DOM component libraries break the React Native build. Share design tokens, never components.',
            },
          ],
          patterns: [
            {
              group: ['@investigator/ui/*', 'react-dom', 'react-dom/*', 'next', 'next/*'],
              message: 'Web-only dependency. Not importable from the mobile companion (ADR-0004).',
            },
          ],
        },
      ],
    },
  },

  // Plain Node scripts beside an app (`apps/*/scripts/*.mjs`, e.g. the bundle budget). Not
  // TypeScript, so nothing declares Node's globals for them.
  {
    files: ['apps/*/scripts/**/*.mjs'],
    languageOptions: { globals: { console: 'readonly', process: 'readonly' } },
  },

  // The web apps: Next.js's own rules (the core-web-vitals set catches `<img>` without sizes,
  // synchronous scripts and the like), and the design-system rule that feature code carries no
  // raw values. Every colour, length and duration is a token (packages/ui-tokens), which is the
  // only place one may be written. `tokens.css` resets Tailwind's palette, so `bg-red-500` does
  // not exist; this catches what a stylesheet cannot: a hex, an arbitrary `w-[13px]`, a `200ms`.
  {
    files: ['apps/app-web/src/**/*.{ts,tsx}'],
    plugins: { '@next/next': nextPlugin },
    settings: { next: { rootDir: 'apps/app-web/' } },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
      'no-restricted-syntax': [
        'error',
        ...['Literal', 'TemplateElement'].flatMap((node) => {
          const value = node === 'Literal' ? 'value' : 'value.raw';
          return [
            {
              selector: `${node}[${value}=/#[0-9a-fA-F]{3,8}\\b/]`,
              message: 'Raw colour. Use a colour token (design-system).',
            },
            {
              selector: `${node}[${value}=/\\b(rgba?|hsla?|oklch|oklab)\\(/]`,
              message: 'Raw colour. Use a colour token (design-system).',
            },
            {
              selector: `${node}[${value}=/-\\[[^\\]]*\\d[^\\]]*\\]/]`,
              message:
                'Arbitrary Tailwind value. Use a token utility, or `(--token)` for a token without one (design-system).',
            },
            {
              selector: `${node}[${value}=/\\b(duration|delay)-\\d+\\b/]`,
              message:
                'Raw duration. Use a motion token: `duration-(--duration-fast)` (animation).',
            },
            {
              selector: `${node}[${value}=/\\b\\d+m?s\\b/]`,
              message:
                'Raw duration. Use a motion token: `duration-(--duration-fast)` (animation).',
            },
          ];
        }),
      ],
    },
  },

  // NestJS dependency injection reads constructor parameter types at runtime from
  // `design:paramtypes`, which `emitDecoratorMetadata` writes at compile time. A
  // type-only import erases the value, so the metadata degrades to `[Function]`:
  //
  //   import { Dep } from './dep'       -> design:paramtypes [dep_1.Dep]
  //   import type { Dep } from './dep'  -> design:paramtypes [Function]
  //
  // Two consequences, both silent. DI can no longer resolve the provider, and a
  // `@Body() dto: SomeDto` parameter loses its class metatype, so ValidationPipe
  // skips the DTO entirely -- taking `whitelist` and `forbidNonWhitelisted` mass
  // assignment protection (main.ts) with it. Unit tests do not catch either,
  // because they construct services with `new` rather than through the container.
  //
  // typescript-eslint documents this rule as incompatible with
  // emitDecoratorMetadata. apps/api is the only package that enables it, so the
  // rule stays on everywhere else. auth.boot.spec.ts is the regression test: it
  // boots the real container and asserts validation still rejects an unknown field.
  {
    files: ['apps/api/**/*.ts'],
    rules: {
      '@typescript-eslint/consistent-type-imports': 'off',
    },
  },
);
