import { ReadonlyVisitor } from '@nestjs/swagger/plugin';
import * as ts from 'typescript';

/**
 * The OpenAPI metadata `@nestjs/swagger`'s compiler plugin would add at build time (T-136).
 *
 * The plugin reads each DTO's TypeScript types and class-validator decorators — `@Length`,
 * `@Min`, `@Matches`, `@IsIn` — and describes them in the OpenAPI document. It runs only inside
 * `nest build`; this API builds with plain `tsc` (and tests with oxc), so without it every request
 * schema in `/api/docs-json` was empty. This runs the plugin's own visitor over the source instead
 * — the same approach as the Nest CLI's metadata generator for SWC builds — and prints the result
 * as `src/metadata.ts`, which `bootstrap.ts` loads before building the document.
 *
 * The file is generated, committed, and checked: `openapi.spec.ts` regenerates it and fails when
 * the committed copy is stale. `pnpm --filter api openapi:metadata` writes a fresh one.
 */
export function generatePluginMetadata(tsconfigPath: string, srcDir: string): string {
  const visitor = new ReadonlyVisitor({
    pathToSource: srcDir,
    classValidatorShim: true,
    introspectComments: true,
    dtoFileNameSuffix: ['.dto.ts'],
    controllerFileNameSuffix: ['.controller.ts'],
    readonly: true,
  });
  const program = ReadonlyVisitor.createTsProgram(tsconfigPath);
  for (const file of program.getSourceFiles()) {
    // tsconfig.json leaves specs out, so only the application's own source is read.
    if (!file.isDeclarationFile) visitor.visit(program, file);
  }

  const f = ts.factory;
  const collected = visitor.collect();
  // Per class the visitor gives either a node, or a record of them (a model's properties, a
  // controller's methods): records become object literals, nodes are printed as they are.
  const literal = (value: ts.Node | Record<string, unknown>): ts.Expression =>
    'kind' in value && typeof value.kind === 'number'
      ? (value as ts.Expression)
      : f.createObjectLiteralExpression(
          Object.entries(value).map(([key, inner]) =>
            f.createPropertyAssignment(
              f.createIdentifier(key),
              literal(inner as ts.Node | Record<string, unknown>),
            ),
          ),
          true,
        );
  const sections = (Object.keys(collected) as Array<keyof typeof collected>).map((section) =>
    f.createPropertyAssignment(
      f.createIdentifier(section),
      f.createArrayLiteralExpression(
        collected[section].map(([importExpression, classes]) =>
          f.createArrayLiteralExpression([
            importExpression,
            literal(classes as Record<string, unknown>),
          ]),
        ),
        true,
      ),
    ),
  );
  const metadata = f.createObjectLiteralExpression(
    [
      f.createPropertyAssignment(
        f.createStringLiteral(visitor.key),
        f.createObjectLiteralExpression(sections, true),
      ),
    ],
    true,
  );
  const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });
  const printed = printer.printNode(
    ts.EmitHint.Expression,
    metadata,
    ts.createSourceFile('metadata.ts', '', ts.ScriptTarget.Latest),
  );
  const types = Object.entries(visitor.typeImports)
    .sort(([a], [b]) => a.localeCompare(b))
    // Each expression is `await import("…")`; the module itself is what is wanted.
    .map(([path, expression]) => `["${path}"]: ${expression.replace(/^await /, '')}`)
    .join(', ');

  // Static imports, not the plugin's `import()`: under Node16 resolution a dynamic import in this
  // CommonJS package would need `.js` on every path, and the modules are loaded by AppModule anyway.
  // The loader awaits each module reference, which a module object satisfies as well as a promise.
  const body = `const t = {${types}};\n    return ${printed};`;
  const paths = [...new Set([...body.matchAll(/import\("([^"]+)"\)/g)].map((m) => m[1]!))].sort();
  const names = new Map(paths.map((path, i) => [path, `m${i}`]));
  const linked = body.replace(/import\("([^"]+)"\)/g, (_, path: string) => names.get(path)!);

  return [
    '// Generated by src/common/openapi/metadata.generator.ts — do not edit. Regenerate with',
    '// `pnpm --filter api openapi:metadata`; openapi.spec.ts fails when this copy is stale.',
    ...paths.map((path) => `import * as ${names.get(path)!} from '${path}';`),
    '',
    'export default async () => {',
    `    ${linked}`,
    '};',
    '',
  ].join('\n');
}
